language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database badgenator_test;' -U postgres
